# 下面两行是指明依赖库的来源地址
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Artsy/Specs.git'

# 说明平台是ios，版本是9.0
platform :ios, '9.0'

# 忽略引入库的所有警告（强迫症者的福音啊）
inhibit_all_warnings!

use_frameworks!

target 'XinYiFu' do



pod 'SnapKit'
pod 'Then'
pod 'Moya'
pod 'Kingfisher', '~> 3.13.1'
pod 'HandyJSON','~> 4.1.3'
pod 'Reusable'
#pod 'LLCycleScrollView'
pod 'MJRefresh'
pod 'MBProgressHUD'
pod 'HMSegmentedControl'
pod 'IQKeyboardManagerSwift'
pod 'EmptyDataSet-Swift','~> 4.0.5'
pod 'CLImagePickerTool'
pod 'LTScrollView'
pod 'ZLaunchAd'
pod 'SwiftyJSON'
pod 'RxSwift',    '~> 4.0'
pod 'RxCocoa',    '~> 4.0'

end
